services:
  cardservice:
    build: .
    ports:
      - "2024:2024"
    environment:
      - "DATASOURCE_URL=jdbc:mysql://card-service@mysql/card-service"
      - "DATASOURCE_USERNAME=card-service"
      - "DATASOURCE_PASSWORD=password"
      - "TOKEN_SECRET=coconut"
      - "TOKEN_DURATION=1239553"
      - "TOKEN_HEADER=Authorization"
      - "TOKEN_PREFIX=Bearer "
    depends_on:
      mysql:
        condition: service_healthy
    entrypoint:
      - "java"
      - "-jar"
      - "target/card-service-latest.jar"
  mysql:
    image: mysql:latest
    environment:
    - "MYSQL_USER=card-service"
    - "MYSQL_PASSWORD=password"
    - "MYSQL_RANDOM_ROOT_PASSWORD=true"
    - "MYSQL_DATABASE=card-service"
    ports:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      start_period: 3s
      timeout: 2s
      retries: 10