server:
  port: 2024
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:

spring:
  data:
    rest:
      limit-param-name: limit
      page-param-name: start
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  devtools:
    restart:
      exclude: logs/**
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        formatsql: true
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
  liquibase:
    change-log: classpath:/config/liquibase/master.xml

    